### PR TITLE
The author should merge their own pull requests

### PR DESCRIPTION
**Pull request by jgorset**

### CODE REVIEW

**Comment by 3lvis** [comment]
Doesn't have that sense of shared responsibility that I liked from PRs.

:-1:

**Comment by jgorset** [comment]
It's still there, though, @3lvis; you're giving it the thumbs up, so I guess you're on the hook if it's crap?

**Comment by jgorset** [comment]
Maybe I should mention the rationale for doing it; who better to resolve merge conflicts and ship the code than the person who wrote it? I'd be pretty scared to deploy a big-ass pull requests from someone else, anyway, in case something goes wrong.

**Comment by 3lvis** [comment]
>I'd be pretty scared to deploy a big-ass pull requests from someone else.

For me is all about trust, is a problem if we don't trust in each other to do our work properly.

**Comment by jgorset** [comment]
Hey, I don't always trust myself to do my work properly. I'm no @ealmdahl!

**Comment by timkurvers** [comment]
There's a certain air of responsibility involved when clicking that merge button. I feel that responsibility should be with the original author, however there's no need to enforce this. Nor should we enforce it to always be someone else, as that leads to uncomfortable situations where someone less familiar with a project or beginner is forced to merge on behalf of someone else.

It's much more important to have good routines on how to determine whether a PR is good to go or not. I think that's probably something that may differ per team and/or project, but in general two or three extra set of eyes on things and not ignoring comments made by others is a must.

**Comment by 3lvis** [comment]
For me shared responsabilty is better than "you did that, it's your fault if something goes wrong".

**Comment by JozoSalt** [comment]
Isn´t the 'ok' you give on the pull request part of a shared responsibility ?

**Comment by 3lvis** [comment]
I agree, I just don't see why is so bad that the "ok" goes followed by a merge.

**Comment by jgorset** [comment]
I guess it depends on the nature of the pull request. If it entails shipping the code (like https://github.com/hyperoslo/hyper-sentry/pull/9, for example), there's more to it than just hitting that button.

Should we compromise that anyone can _merge_ a pull request, but the person who wrote it should _ship_ it?

**Comment by timkurvers** [comment]
Have tried to find the Rails core guidelines but can't seem to find any.

Found this:

> We have developers merge in their own pull request so they have better visibility into when their code gets deployed.
> — [NewRelic](https://blog.newrelic.com/2012/12/19/experimenting-with-github-pull-requests/)

And another:

> To make sure nobody introduces changes into our production system without review, we have a strict rule that you can never merge your own code. This rule is not enforced through technology, but a strict team policy.
> — [Codeship](https://blog.codeship.com/github-code-review/)

That leads me to believe that the golden approach is somewhere in the middle.

Strikes me a a good trade-off @jgorset :+1:

**Comment by zenangst** [comment]
I think I'm in favor or having you merge your own pull request if you have had a second (or third) pair of eyes on it. Having a good sign-off routine for when a pull request is "ready to go" would be paradigm.

Strikes me as odd that people from other teams should take on that kind of responsibility when they have no way of having the same context as the person who made it. However, if you are on the same team, then it might be fine to merge each others pull request but I don't see that as a must, this could be done by the last guy signing off instead of having the original owner do it. Might be more efficient.

As for placing blame, you shouldn't do that regardless and that's a whole different chapter/discussion.

**Comment by vadymmarkov** [comment]
I think it's a good approach to merge each others pull requests when you are in the team and familiar with that project. Merge could be done by anyone who is confident about it, you shouldn't be forced to do that, but anyway there is a chance just to review code and send some feedback.

**Comment by 3lvis** [comment]
Seems that you guys are talking about a very specific thing: merge/deployment. In native we don't have those.

Also I think we can change our document to state that only a member of the team can merge the pull request but not you.

For open source projects should be fine that anyone can merge.

**Comment by RamonGilabert** [comment]
I agree with @3lvis on this one. I feel there are two parts here, the open source pulls and the client projects, in the open source pulls everyone can marge a pull request and in the client projects I see the point in the team members to merge the pull requests.

I feel that pull requests are a pretty strong thing and should be done by two people or more, one does the pull, other people comment and the other one merges, I thing that way we all agree that this pull is good in the same way that, if you do a pull request and others comment and agree, then you can merge. But I would do that only if that happens.

SO! I think we should leave it the two ways: everyone can merge the pull if they are in the team or at least know what they are talking about, and also if everyone comments your pull saying, nice! Then yes, you can merge it, but it might be merged already by someone else before.

**Comment by jgorset** [comment]
This is why I @hyperoslo.

**Comment by timkurvers** [comment]
I don't see why open vs private source would make any difference. On any given project you'll have a set of developers more in-the-know than others. For private client projects this would be members of the team, whereas for open-source projects this would be the developers that have shaped the project.

It's these core developers' QA routine that should ultimately decide whether a pully goes through. That is, if @jgorset, @sindrenm and me were to :+1: a pull request on an iOS repo, we should probably wait for feedback from one of the iOS guys, just to be sure.

@3lvis What's the reasoning behind opening a duplicate PR? It could split an otherwise neatly linear discussion.

**Comment by 3lvis** [comment]
@timkurvers 

screen shot 2015-05-06 at 10 10 33 pm

**Comment by 3lvis** [comment]
>Whereas for open-source projects this would be the developers that have shaped the project

@timkurvers In idea that sounds good, in practice isn't really how it works, you don't always have this huge open source projects where there's a core team of developers. We have smaller open source projects where only one developer is working. So, instead of having a document with tons of instead is better to document the rule and apply exceptions where it makes sense.

**Comment by timkurvers** [comment]
Would one developer change anything? One could have the entire tech team weighing in if they want to, but you would definitely want that 'core' developer to be part of the QA process. I don't see how this is an exception.

**Comment by 3lvis** [comment]
One developer = "core developer".

If that developer makes a PR anyone giving feedback = "Not core developer" = Not entitled to give feedback?

**Comment by timkurvers** [comment]
Why wouldn't people be able to provide feedback?

**Comment by 3lvis** [comment]
@timkurvers Because not core developer.

**Comment by timkurvers** [comment]
I never said anything of the sort.

> One could have the entire tech team weighing in if they want to, but you would definitely want that 'core' developer to be part of the QA process.

That is, if only one person is truly in the know about the project, you most definitely want at the very least that person involved.

**Comment by 3lvis** [comment]
Why you would want the entire tech team to review your code?

**Comment by 3lvis** [comment]
@timkurvers I think I understood what you mean, I updated my PR to reflect what I understood. 

https://github.com/hyperoslo/playbook/pull/34/files

**Comment by ealmdahl** [comment]
Just to chip in my 2 cents: I think a developer with the proper context (core developer, if you like) should do the merging. Let me illustrate with two scenarios:

Devs A and B are the core team on a project. They should review each others' PRs, and both have enough context to merge (and potentially deploy). Dev C may comment and approve of the code quality per se, but probably does not have enough context to know if the PR does what it is supposed to with regards to spec/requirements. It should be up to the core team to consider the comments from C and when to merge.

Then, in the case that Dev C wants to help out with something in the project, he implements his stuff and makes a PR. A and/or B reviews and decides if that PR is good to go and when to merge it. Dev C should probably NOT be responsible for the merge in this case.

Lastly, in the case that the core team is only Dev D (which should not be the case, but probably will be quite a few times...), his code should be reviewed by AT LEAST one other dev, preferably two, but the only one with enough context to actually know what and when to merge is himself.

For other and edge cases: keep calm and stay pragmatic :hamster:

**Comment by fespinoza** [comment]
when a PR is merged (or approved to be merged) it's supposed to be ready to deploy/ship/pack it

the creator of the PR must mention if there are risks with the changes introduced (ex: this change can potentially break the iOS client because of this) or mention backwards incompatibilities

if a person reviews a PR, for me mergin the PR is a sign of the intention of the PR being approved, because some times a simple :+1: is not a good enough sign

in any case of failure is responsability of the PR author to fix that, not the mergin person

that is my avenger opinion

**Comment by 3lvis** [comment]
Doesn't matter who comments, it's about who merges, and only having people part of the core team to merge makes total sense to me.

I updated my PR to state this (my PR points to this PR, btw @jgorset):

https://github.com/hyperoslo/playbook/pull/34

------------------------------------------

#### Who merges the pull request?

Let's say you're working on a pull request. The tests are green and you're ready
to merge. Who does that? If you're working on a library, any collaborator of the 
project can merge it. If you're working on an app, another member of your team should 
merge it.

Once the pull request is accepted the merger should delete the branch.

**Comment by sindrenm** [comment]
Great discussion, people!

**Comment by jgorset** [comment]
I let this run for a few days to make sure everyone had a chance to chime in, and I've really enjoyed following the discussion. I think it's great that we feel strongly about the little things — not only does that make us top notch, but it also goes a long way to show that we don't have bigger things to worry about.

It seems to me that there are good arguments on either side, but that we all agree on one thing; it's fine (and indeed encouraged) for anyone to weigh in on pull requests to any project, but the person who merges should be someone who can be considered a _core contributor_ to it. For a one-man show that's the one man*, and for a team of two or three it should probably be one of the other two.

Incidentally, that policy would make sense for both public and private repositories.

\* We'll continue to avoid one-man shows as much as possible, but it's bound to happen from time to time; the other developer could be out sick, or the project just isn't big enough for it to make sense to have more than one developer.

**Comment by timkurvers** [comment]
Best summation ever is epic :heart:

**Comment by jgorset** [comment]
I made another commit that I think summarizes things, but let me know if you think I got it wrong. Let's leave this open for a few more days just to let it sink in.

**Comment by RamonGilabert** [comment]
I agree @jgorset! :) And for the delete branch thing, it's more clear in your commit! So perfect! :)

**Comment by zenangst** [comment]
@jgorset 
giphy-29

**Comment by jgorset** [comment]
Okay then! It's official! Thanks everyone!

**Pull request merged**
