### PR TITLE
Improve documentation on workflow

### PR DESCRIPTION
**Pull request by jgorset**
Jeanett asked me to document agile, so I went over this from way back when and changed a few things.

It's easier to [read without a diff](https://github.com/hyperoslo/playbook/blob/improve/workflow/WORKFLOW.md).

### CODE REVIEW

**Comment by sindrenm** [comment]
@jgorset: I took the liberty to update your link, seeing as it pointed to the file in a specific commit (44adc13) where you'd probably want it to point to the file on the latest commit in the branch. :wink:

**Comment by jgorset** [comment]
Thanks @sindrenm!

**Comment by sindrenm** [comment]
Is there a reason you're calling this by the very generic term “agile” and not something closer to “Scrum”? Just asking since it involves sprints (planning, review, retrospective), which is not present in, say, Kanban.

**Comment by jgorset** [comment]
Good question. The document used to touch on that, but I removed it to keep things simple. I think the most important thing is not to tell Scrum from Kanban, but simply to do the things that make sense from either methodology (and maybe some things from neither).

I like to think of agile as just a big box of tools that you can pick and choose from to solve your problem, and that doing so is better than subscribing to any one methodology.

**Comment by jgorset** [comment]
I screwed up the rebase and a wild @3lvis appeared. :grin:

**Comment by jgorset** [comment]
Anyway, I'll take the liberty of merging this if you're cool with it, @sindrenm.

**Comment by sindrenm** [comment]
I agree, the best is probably to just document _how we do it_, or _how we prefer_, and basically have our own agile methodology. And this definitely looks like that. So great stuff!

**Comment by jgorset** [comment]
Thanks!

**Pull request merged**
