### PR TITLE
Improve assignment letter

### PR DESCRIPTION
**Pull request by NSElvis**
The idea is to be able to just show this to applicants, or even better, point them here from our iOS applicants web page. :)

### CODE REVIEW

**Comment by sindrenm** [comment]
Seems cool. I don't know anything about Hyper Recipes, though. :stuck_out_tongue: 

Also, we don't *actually* hire people only based on their cool name, do we?

**Comment by NSElvis** [comment]
@sindrenm I would totally hire a guy called Steve Jobs.

**Comment by sindrenm** [comment]
I suppose he wouldn't require much moneys, so …

**Comment by NSElvis** [comment]
@sindrenm btw, this is under `iOS/HYPER_RECIPES.md` :)

**Comment by timkurvers** [comment]
We might want to tweak that post scriptum to drop the colon (http://english.stackexchange.com/questions/19311/punctuation-after-p-s) as well as rewrite `I` to `we` here:

> Thanks and I hope you enjoy making some recipes.

**Comment by NSElvis** [comment]
@timkurvers I hope it's fine to merge now, made some final fixes

**Comment by timkurvers** [comment]
Another iOS team member should have a look at this, but s'looking great!

**Comment by NSElvis** [comment]
@timkurvers I don't think it needs to be that way. Maybe that would apply for an iOS repo.

**Comment by timkurvers** [comment]
Considering this is under `iOS/HYPER_RECIPES.md` that'd probably be a good idea?

**Comment by NSElvis** [comment]
@timkurvers Okay, if you think so :)

@zenangst would you mind taking a look at this?

**Comment by NSElvis** [comment]
@timkurvers I fixed the issue! Now should be safe to merge :dancer:

**Comment by NSElvis** [comment]
I'm moving this to https://github.com/hyperoslo/iOS-playbook, thanks everyone for your support and have a nice day.

**Comment by NSElvis** [comment]
@zenangst would you mind taking a look at this?

**Comment by sindrenm** [comment]
YOLO!

**Comment by timkurvers** [comment]
Which issue was that @elvis?

**Comment by NSElvis** [comment]
@timkurvers What do you mean?

**Comment by timkurvers** [comment]
> @timkurvers I fixed the issue! Now should be safe to merge :dancer:

**Comment by NSElvis** [comment]
@timkurvers Oh, where's that? Can't see it.

**Comment by NSElvis** [comment]
196v0lhtug35mjpg

**Comment by zenangst** [comment]
Moar changes, I guess I can't be the one to merge anymore? :grin:

**Comment by jgorset** [comment]
I'll do it! I like this a lot!

**Pull request merged**
