### PR TITLE
Make things better (but mostly write about opening a bank account)

### PR DESCRIPTION
**Pull request by jgorset**

### CODE REVIEW

**Comment by RamonGilabert** [comment]
You could also put that it's a paaaaaaain! :smile: and takes 5 weeks to open one.

**Comment by jgorset** [comment]
Oh! Which part takes 5 weeks, @RamonGilabert? Waiting for the tax authorities to give you a national ID number, or the bank to get the account opened?

**Comment by RamonGilabert** [comment]
You wait 10 days to get the D-Number, once you have that, then you go to the bank and then you have to wait 3 weeks in order for them to send you some papers to your house (the contract of the account), and once you have that, send it back to the bank, this will take another week for them to have the papers. Once they got them, they'll send you the card or whatever. So 5 to 6 weeks. :smile:

**Comment by jgorset** [comment]
Aha! You wrote about that, @richardoti – were you able to sign that contract in your first appointment with the bank, so as to avoid all the snail mail?

**Comment by RamonGilabert** [comment]
I could mention at some point that Skandiabanken it's fast as hell! :)

**Pull request merged**
