### PR TITLE
Improve: assignment letter

### PR DESCRIPTION
**Pull request by NSElvis**
> If you have any cool libraries in GitHub that you can show us, please send them to us, especially if it's one that you use on a daily basis.

I'll prefer to keep it this way, it sucks when you see libraries that were made just because someone had too much spare time, I think someone should do things because they want to use them.

>Please send us a link to your Hyper Recipes repository when it's created, and please remember to write concise and understandable commits.

Very rarely people make *good* commits, I think it's important to point this out.

> and remember, don't feed the troll, he's on a diet.

Which troll?

### CODE REVIEW

**Comment by timkurvers** [comment]
I'd drop the `libraries` and `GitHub` bits, they're not required.

**Comment by timkurvers** [comment]
> Please send us a link to your Hyper Recipes repository when it's created ..

We'd like to receive it once it's ready I suppose, not when it's empty?

**Comment by zenangst** [comment]
`would love to share`, was intended to imply passion.

**Comment by zenangst** [comment]
@NSElvis we are name dropping both dragons & unicorns, and the troll raises an eyebrow? :grin:

**Comment by NSElvis** [comment]
> I'd drop the `libraries` and `GitHub` bits, they're not required.

We've gotten source code extracted from random apps before, it's not helpful,

**Comment by NSElvis** [comment]
@zenangst Was it meant as an advise? Didn't saw the context :)

**Comment by NSElvis** [comment]
@timkurvers 

> We'd like to receive it once it's ready I suppose, not when it's empty?

I was thinking in this more like an early collaboration thing, for example you see something that catches your eye you can mention it early so you get to hear their side of things and start collaborating early. Maybe even feature PRs and stuff like that could be useful.

**Comment by zenangst** [comment]
@NSElvis didn't your mother teach you to never feed trolls?

**Pull request merged**
