### PR TITLE
Improve clarity on who merges

### PR DESCRIPTION
**Pull request by 3lvis**

### CODE REVIEW

**Comment by jgorset** [comment]
Wouldn't this pretty much just revert my pull request, @3lvis? I've been looking at the diff and it seems to pretty much just change it back to what it currently says on `master`.

**Comment by 3lvis** [comment]
@jgorset It states that only people involved in the project should merge the pull request. I think it's a middle ground between your proposal and what we had before.

**Comment by timkurvers** [comment]
Sidenote: this PR should really be set to merge into `master` as opposed to `merging-pull-requests`.

**Comment by jgorset** [comment]
I think it's fine to merge it into mine if it's keeping the branch up to date with the discussion, though, don't you think @timkurvers?

**Comment by timkurvers** [comment]
That was my initial standpoint against opening a separate PR if it belongs in yours :smile:

**Comment by jgorset** [comment]
Haha, right, so it doesn't tempt anyone to derail the discussion into two separate threads? I guess in that case you could have just pushed the commits straight to my branch, @3lvis.

**Comment by jgorset** [comment]
I'll merge this, anyway, @3lvis, and I'm summing up the discussion into something that might mean we could make it even more clear.

**Comment by 3lvis** [comment]
@jgorset I was afraid that pushing my changes into your code would be a bit rude.

**Comment by jgorset** [comment]
That makes sense, @3lvis. :-)

**Pull request merged**
