### PR TITLE
Don't apply for a visitor's visa

### PR DESCRIPTION
**Pull request by jgorset**
... because that's just not how it works! You apply for a residence permit for skilled workers.

### CODE REVIEW

**Comment by timkurvers** [comment]
No badgers? :cry:

**Comment by jgorset** [comment]
No badgers! In fact probably what we'll do is help people out with viewing apartments once they get here, because that can be a pretty daunting thing to do on your own.

**Comment by jgorset** [comment]
Thanks @RamonGilabert! :cake:

**Comment by sindrenm** [comment]
:+1:

**Pull request merged**
