### PR TITLE
Write about how to get here

### PR DESCRIPTION
**Pull request by jgorset**

### CODE REVIEW

**Comment by NSElvis** [comment]
I wish I had this when I came, now thinking about it is just shadows and snø.

**Comment by jgorset** [comment]
Haha @NSElvis.

**Comment by jgorset** [comment]
You swam, right?

**Comment by NSElvis** [comment]
@jgorset: Cargo is a better word.

**Comment by sindrenm** [comment]
Cardio!?

**Comment by NSElvis** [comment]
:tada: :cake: :tada:

**Comment by jgorset** [comment]
Thanks @NSElvis!

**Pull request merged**
