### PR TITLE
Remove reference to "bro code"

### PR DESCRIPTION
**Pull request by espenhogbakk**
In light of stuff like "Gamer gate" and other sexist things on the Internet, Hyper should maybe not use words like this. It might come of as sexist. We should encourage woman to work at Hyper, and the use of phrases like this might be misinterpreted.

### CODE REVIEW

**Comment by espenhogbakk** [comment]
If this is approved, we also need to change the description in the Github repo.

**Comment by timkurvers** [comment]
:+1:

**Comment by sindrenm** [comment]
Aww … I suppose you have a point, though.

**Comment by jgorset** [comment]
Me three.

**Comment by jgorset** [comment]
I changed the description of the repository to "how we do things", but if anyone has a better idea that'd be cool, too.

**Pull request merged**
