### PR TITLE
More about tax reduction for foreigners

### PR DESCRIPTION
**Pull request by toothfairy**

### CODE REVIEW

**Comment by sindrenm** [comment]
:+1: for _No description provided._ :smiley:

**Comment by toothfairy** [comment]
@sindrenm commit title is nearly as long as commit diff. Should I add a description to make it even more disproportional? I can do that. Including that comment, all the conversation about a short change will be 10 as bigger as the change itself. Basta

**Comment by sindrenm** [comment]
Nah, you don't have to do that. :stuck_out_tongue:

**Comment by jgorset** [comment]
Nica!

**Pull request merged**
