### PR TITLE
Talk about spot.hyper.no

### PR DESCRIPTION
**Pull request by jgorset**

### CODE REVIEW

**Comment by jgorset** [comment]
You should probably have the honor of merging this, @gauravtiwari. :wink:

**Comment by gauravtiwari** [comment]
@jgorset done :+1:

**Comment by zenangst** [comment]
Spotme is just fantastic!

**Comment by jgorset** [comment]
Yeah, it's really nice – great job @gauravtiwari!

**Comment by gauravtiwari** [comment]
:smile: Team effort @jgorset.

**Comment by gauravtiwari** [comment]
@zenangst awesome :smile: :cake:

**Pull request merged**
