### PR TITLE
Talk about rooms.hyper.no

### PR DESCRIPTION
**Pull request by jgorset**

### CODE REVIEW

**Comment by jgorset** [comment]
I figure the instructions on how to use microphones and cameras aren't as necessary now that we've already set that up.

**Comment by ohenrik** [comment]
Sort of true, however, these are general principles that might be good to still have written down so we know some background about why we designet the rooms like we did. Anyway this text could be improved :) (not the text you added, i mean the text that was removed). 

Also the point about having all virtual meetings can sometimes be a good point that goes beyond just people sitting at the office.

Thats my 2¢ :)

**Comment by jgorset** [comment]
Yeah, you're right. I restored it. :smile:

**Comment by ohenrik** [comment]
Sweet! :)

**Comment by jgorset** [comment]
Feel free to merge, @hyperoslo/everyone! There's :cake: if you do!

**Comment by ohenrik** [comment]
Hope the :cake: is not a lie! :D

**Pull request merged**
